export { buildAggregateRating } from 'lib/schema/aggregateRating'
export type { AggregateRating } from 'lib/schema/aggregateRating'
export { buildApartmentComplexSchema } from 'lib/schema/apartmentComplex'
export type { ListingInventorySnapshot } from 'lib/schema/apartmentComplex'
export { buildBreadcrumbListSchema } from 'lib/schema/breadcrumbList'
export type { BreadcrumbSegment } from 'lib/schema/breadcrumbList'
export { buildFaqPageSchema, TURNBERRY_FAQ_ITEMS } from 'lib/schema/faqPage'
export type { FaqItem } from 'lib/schema/faqPage'
export { TURNBERRY_GEO } from 'lib/schema/geo'
export { buildOrganizationSchema } from 'lib/schema/organization'
export { buildRealEstateAgentSchema } from 'lib/schema/realEstateAgent'
